# Generated by Django 4.1.7 on 2023-03-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0003_actor_foto_director_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
