# Generated by Django 4.1.7 on 2023-03-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0004_actor_biografia_director_biografia_pelicula_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='foto',
            field=models.ImageField(blank=True, default='blank.png', null=True, upload_to='actor'),
        ),
        migrations.AlterField(
            model_name='director',
            name='foto',
            field=models.ImageField(blank=True, default='blank.png', null=True, upload_to='director'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(blank=True, default='blank.png', null=True, upload_to='pelicula'),
        ),
    ]
